apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: expense
  name: expense-trainee
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"] #access only to pod
  verbs: ["get", "watch", "list"] #actions allowed

---

apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "suresh" to read pods in the "expense" namespace.
# You need to already have a Role named "expense-trainee" in that namespace.
kind: RoleBinding
metadata:
  name: expense-trainee
  namespace: expense
subjects:
# You can specify more than one "subject"
- kind: User
  name: suresh # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: expense-trainee # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: expense
  name: expense-admin
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"] #access only to pod
  verbs: ["*"] #actions allowed

---

apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "suresh" to read pods in the "expense" namespace.
# You need to already have a Role named "expense-trainee" in that namespace.
kind: RoleBinding
metadata:
  name: expense-trainee
  namespace: expense
subjects:
# You can specify more than one "subject"
- kind: User
  name: ramesh # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: expense-admin # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

